# Generated by Django 3.0.4 on 2021-02-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='addrss',
            new_name='address',
        ),
    ]
